# Generated by Django 5.2.6 on 2025-09-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_is_sent_alter_reminder_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='caretaker',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='patient',
        ),
        migrations.AddField(
            model_name='reminder',
            name='firebase_caretaker_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='firebase_patient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
