# Generated by Django 5.2.6 on 2025-09-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(default='2026-12-31'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='location',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_id',
            field=models.CharField(default='MED001', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='shop_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicine',
            name='shop_name',
            field=models.CharField(default='Default Shop', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='username',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
