# Generated by Django 5.1.4 on 2025-11-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_medicine_expiry_date_medicine_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="medicine_id",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="password",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="shop_id",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="username",
        ),
        migrations.AlterField(
            model_name="medicine",
            name="expiry_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="location",
            field=models.CharField(default="Hospital Store", max_length=100),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="shop_name",
            field=models.CharField(default="Main Pharmacy", max_length=100),
        ),
    ]
